baseURL = 'http://plus360.eu/'
theme = "plus360-theme"

defaultContentLanguage = 'de'


[languages]
[languages.de]
languageCode = 'de'
title = 'plus360 Webseite'

[languages.en]
languageCode = 'en-us'
title = ' plus360 Web Site'

[languages.ru]
languageCode = 'ru'
title = 'plus360 интернет сайт'